    
FROM jupyter/base-notebook
#jupyter/scipy-notebook
# Maintainer Sebastian Schmidt

USER root

RUN pip install 'ggplot==0.6.8'

RUN apt-get update && apt-get install -yq --no-install-recommends \
    python3 \
    python3-pip \
    liblas-c3

COPY requirements.txt /tmp/

RUN conda update -n base conda

RUN pip3 install --requirement /tmp/requirements.txt && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
    
RUN mkdir data

